### ISSUE TITLE
Request: Remove Library tab button in DM list

### ISSUE THREAD

**Issue by SRoy89** [BleedingBD/plugin-RemoveChatButtons#1]
Similar to the Nitro tab and Friends tab, I also want to request an option to remove the Library tab. Thanks! 
![image](https://user-images.githubusercontent.com/61577078/193776036-4bb5905d-eb0f-436e-a60d-91771d5f4c22.png)
![image](https://user-images.githubusercontent.com/61577078/193775953-5355ff6a-c94c-4a40-ae95-9f7018d1ed67.png)

**Comment by QbDesu** [comment]
There is an option to turn it off under the `Advanced` config tab:
![image](https://user-images.githubusercontent.com/5641607/193809867-548cb4a2-b8d2-41be-ad1b-a75d936a6975.png)
