### ISSUE TITLE
Feature request: Remove Super Reaction button

### ISSUE THREAD

**Issue by heldheld** [BleedingBD/plugin-RemoveChatButtons#11]
I think this is new, I keep accidentally clicking on it when I want to react with an emoji.

**Comment by 7MXek** [comment]
This would be great. Super reactions are obnoxious.

**Comment by QbDesu** [comment]
This will definitely be added as a feature, at the very least for the buttons in the corner of the messages. Context Menus are their own beast though, so no promises there.

I also can't make any promises about when I will actually get around to implementing it.

**Comment by QbDesu** [comment]
I'm gonna consider this done now. The recent update added support for the message action buttons, not the context menus though. Anything going further can be tracked in its own issue if there is still demand.
