### ISSUE TITLE
still having chat buttons

### ISSUE THREAD

**Issue by DAmNRelentless** [BleedingBD/plugin-RemoveChatButtons#2]
The plugin doesn't work for a few buttons. I still have the gift button and the GIF button although I disabled them
![](https://i.imgur.com/Avjk1wh.png)
![](https://i.imgur.com/WsuCQPB.png)

BD: v1.8.1
Plugin: v1.3.2

**Comment by DAmNRelentless** [comment]
I only have this plugin and channel tabs.

**Comment by Banaanae** [comment]
> I only have this plugin and channel tabs.

doubt this has anything to do with it but when that happened to me i
1. Open any dm
2. go into remave chat button plugins settings  
3. disable and enable everything followed by disable and enable plugin
4. exit back to the dm and it might be fixed

**Comment by DAmNRelentless** [comment]
Didn't help, sadly. Thanks for trying to help tho.

**Comment by QbDesu** [comment]
Since when this was first posted there was some changes to the plugin, especially for compatibility with some themes, so I'm closing this now as this is likely fixed by now. If it isn't feel free to open another issue.

**Comment by DAmNRelentless** [comment]
You know, you could just ask if this was fixed and it isn't. I am also not using any themes.

**Comment by RobinRMC** [comment]
I'm having the same problem. Everything seems to work, except for the GIF and Gift buttons.
