### ISSUE TITLE
I still having the buttons

### ISSUE THREAD

**Issue by GTREDITION** [BleedingBD/plugin-RemoveChatButtons#4]
hello, with some updates with better discord o discord (i am not sure) the plugin don't works correctly
![imagen](https://user-images.githubusercontent.com/53015599/200920787-8081dea1-e701-4d24-8cdf-888bf76d6b3d.png)
Stable 157215
Host 1.0.9007

**Comment by QbDesu** [comment]
That might be an incompatibility issue with your theme. You should be prompted to update to 1.4.0 soon, maybe that fixes it. Otherwise double check if the plugin is enabled in the settings and the settings reflect the buttons you want removed.

**Comment by QbDesu** [comment]
Since when this was first posted there was some changes to the plugin, especially for compatibility with some themes, so I'm closing this now as this is likely fixed by now. If it isn't feel free to open another issue.
