### ISSUE TITLE
Request: Snowsgiving and plugin compatibility 

### ISSUE THREAD

**Issue by Lagomorphius** [BleedingBD/plugin-RemoveChatButtons#5]
Could you add a toggle for the new snowsgiving tab (keep it as a toggle even after it gets removed for next year onward) and add support for hiding buttons on strencher's InvisibleTyping plugin?

**Comment by QbDesu** [comment]
you should be prompted to update to 1.4.0 soon. This adds the features you asked for + a little extra. If this works for you make sure to close the issue.

**Comment by Lagomorphius** [comment]
The typing toggle button comes back after toggling the hiding
