### ISSUE TITLE
Broke with the recent discord update.

### ISSUE THREAD

**Issue by kazuviking2** [BleedingBD/plugin-RemoveChatButtons#7]
Settings doesn't show anything when clicking the arrow.

**Comment by QbDesu** [comment]
This is an issue with Zere's Plugin Library and not RemoveChatButtons, for now all we can do is wait for it to be updated, there is already a PR addressing the issue.

(Please refrain from commenting there)
https://github.com/rauenzi/BDPluginLibrary/pull/176

**Comment by QbDesu** [comment]
Make sure to update to the latest version and it should work again.
